openapi: 3.1.0
info:
  title: Rates API method signature and return type
  version: 1.0.0
components:
  schemas:
    requestRates:
      description: >-
        The request rates facilitate the client requesting a rate(s) update from
        Citi, following the input properties.
      type: object
      properties:
        symbol:
          type: string
          maxlength: 6
          example: EURUSD
          description: >
            Input either- 

            - Nothing in the ccy pair field, in which case Citi will return
            rates for all ccy pairs/tenors for which the clnent is authorised.
            Citi knows which client it’s dealing with from the connection
            username.


            - A single ccy pair if the client requires a refresh of a particular
            rate. This is a 6 character string Please 

            discuss with sales on your preference of sending the value of
            currency pair in either BaseTerm format or 

            alphabetic sort order  
        clientAccount:
          type: string
          description: The Client Account id
          example: client1
    Rates:
      type: array
      items:
        type: object
        required:
          - rateSetId
          - ccyPair
          - tenor
          - bidSpotRate
          - offerSpotRate
          - bidForwardPoints
          - offerForwardPoints
          - midPrice
          - validUntilTime
          - isValid
          - baseCurrency
          - ratePrecision
          - valueDate
          - bidOutrightRate
          - fixingRate
        properties:
          rateSetId:
            type: integer
            description: The Citi-defined rate set ID that the rate belongs to.
            example: 123456
          ccyPair:
            type: string
            description: >-
              A six character sorted alpha string comprising two ISO ccy codes
              that the rate applies to.
            example: EURUSD
            maxLength: 6
          tenor:
            type: string
            description: The Tenor for the rate.
            maxLength: 3
            example: SP
          bidSpotRate:
            type: string
            format: double
            description: The Bid Spot Rate for the currency pair.
            example: '1.04'
          offerSpotRate:
            type: string
            format: double
            description: The Offer Spot Rate for the currency pair.
            example: '1.06'
          bidForwardPoints:
            type: string
            format: double
            description: The Bid Forward Points for this tenor (Forward Pricing Only).
            example: '0.01'
          offerForwardPoints:
            type: string
            format: double
            description: The Offer Forward Points for this tenor (Forward Pricing Only).
            example: '0.02'
          midPrice:
            type: string
            format: double
            description: The Mid Price for the rate.
            example: '1.05'
          validUntilTime:
            type: string
            description: >-
              The time and date that this rate will expire. Note-This is held in
              GMT / UTC format: yyyyMM-dd HH:mm:ss.SSS
            example: 2018-10-15 16:30:00.000 GMT
          isValid:
            type: boolean
            description: >-
              A flag that shows that Citi was able to provide the requested
              rate. If this field is false, then midPrice, points, and rates are
              zero.
            example: true
          baseCurrency:
            type: string
            maxLength: 3
            description: The base currency of the currency pair.
            example: EUR
          ratePrecision:
            type: integer
            description: >-
              The number of decimal places to which the rate(s) for this tenor
              should be quoted in regular base/term format.
            example: 2
          isTradable:
            type: boolean
            description: >-
              A flag to indicate whether the rate is tradable by the client
              (TRUE) or is to be used for reference purposes only.
            example: true
          fixingRate:
            type: string
            format: double
            description: >-
              This field and `fixingsource` field will only be populated once a
              month on the agreed NDF fixing date. Will contain the fixing rate
              to be used for this currency pair.
            example: '0'
          fixingSource:
            type: string
            description: >-
              Will contain the fixing source associated with the fixingRate
              field.
            example: Citi New York 15:00 Fixing
            maxLength: 100
          valueDate:
            type: string
            format: date
            description: 'The value date of the rate returned in format: yyyy-MM-dd.'
            example: '2011-05-06'
          drawDownValidUntilTime:
            description: >
              Optional field. The extended time and date that this rate will
              expire for sending draw down orders. This field will be sent only
              if you are enabled for sending pre-order requests. Note: this is
              held in GMT / UTC in format: yyyy-MM-dd HH:mm:ss.SSS.
            example: '2011-05-05 09:30:00.000'
          bidOutrightRate:
            type: string
            format: double
            description: The Bid Outright Rate for this currency pair.
            example: '111.24'
          isMrf:
            description: >-
              Optional field. Applicable when MRF hourly updated rate option
              enabled. Flag indicates whether this is updated rate due to MRF
              True indicates updated rate.
            type: boolean
            example: true
          rateId:
            type: integer
            description: >-
              Optional field. Applicable when MRF hourly updated rate option
              enabled. Unique identifier of a rate. Value is incremental. Used
              for reference purpose to identify latest rate in case of
              incremental version of rate due to MRF.
            example: 456123
